<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>serpent</string>
	</array>
	<key>name</key>
	<string>Serpent</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+|^)(lat)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\d+)</string>
			<key>name</key>
			<string>lat.card.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+|^)(cell)\s+(\d+)\s+(\d+)\s+((fill)\s+(\d+)|(outside|void)|(\w+))</string>
			<key>name</key>
			<string>cell.card.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+|^)(surf)\s+(\d+)\s+(\w+)</string>
			<key>name</key>
			<string>surf.card.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+|^)(nest)\s+(\d+)\s+(\w+)</string>
			<key>name</key>
			<string>nest.card.serpent</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.serpent</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.serpent</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.serpent</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.doublequoted.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
			<string>comment.line.percentage.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+|^)(pin)\s+(\d+)</string>
			<key>name</key>
			<string>keyword.control.pin.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+|^)(fill)\s+(\d+)</string>
			<key>name</key>
			<string>keyword.control.fill.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^a-zA-Z0-9]+|)(ene|set|dep|mat|pin|surf|cell)\s+([0-9a-zA-Z]+)</string>
			<key>name</key>
			<string>keyword.control.serpent</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(set|dep|plot)\b</string>
			<key>name</key>
			<string>support.function.serpent</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(outside|rgb|void)\b</string>
			<key>name</key>
			<string>keyword.control.serpent</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cyl|pz|hexyc|pad|sph|hexxc)\b</string>
			<key>name</key>
			<string>variable.language.serpent</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9]+)([0-9]{3})(\.[0-9]{2}c)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.serpent</string>
	<key>uuid</key>
	<string>78FC54AD-F661-4EED-BB96-2E62F3B8F0CA</string>
</dict>
</plist>
